### ISSUE TITLE
Close when tapping outside lightbox / zooming comments

### ISSUE THREAD

**Issue by pflind** [kthornbloom/Smoothproducts#13]
Wouldn't it be great with zooming capabilities on touch devices? At least I think it's a draw back that you can't view image details if you're using a touch device. Touch devices usually have small screens, which could benefit from a zoom function more so than on desktop devices. I did tests on a Win 10/Edge touch tablet and a iPhone 6 with latest iOS.

Another, small UI thing. When you touch outside the lightbox it should close the lightbox, same behavior as on desktop. This should be fixed. It works on my Win tablet but not on iPhone.

This is a great little script overall, many thanks!

**Comment by kthornbloom** [comment]
Hi, this script has gone through many changes over the years. At one point, it did have zoom that even attempted to use the phone's gyroscope to pan around the zoomed-in image. 

Unfortunately, since I use this on production projects, I've found that most users are annoyed with being zoomed in to a tiny detail. They'd rather see the whole image larger. So that's how I've updated it. Feel free to look back through old versions though!

Touching outside the lightbox should close it. I may have had an old version up on my demo. I just fixed that so you may try it again.

**Comment by pflind** [comment]
Hi, and thank you! 

Touching outside the lightbox doesn't work on iPhone 6. I tested in both portrait and landscape mode. Neither your demo page nor the downloaded local copy works.

**Comment by kthornbloom** [comment]
Thanks for the report! I'll look into it. I've modified this issue to be more related to that bug.

**Comment by yabdab** [comment]
Quick fix.

.sp-lightbox {
  cursor: pointer;
}

**Comment by kthornbloom** [comment]
@yabdab I've added your suggestion. I don't have an iPhone 6 to test with. Let me know if it helps resolve the issue!

**Comment by yabdab** [comment]
@kthornbloom I added it with my own copy here and it works fine.
